site_name: Moat
theme:
  name: material
  features:
    - navigation.expand
    - navigation.path
repo_url: https://github.com/moat-io/moat
dev_addr: localhost:8001

# https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml

nav:
  - Home: index.md
  - Trino and OPA: trino_and_opa.md
  - How it works: how_it_works.md
  - Bundles: bundles.md
  - Provisioning:
      - SCIM2.0: provisioning/scim.md
      - HTTP Connector: provisioning/http_connector.md
      - Resources:  provisioning/resource_ingestion.md
  - Security:
      - API Authentication: security/auth.md
      - Audit: security/audit.md
  - Deployment:
      - Application: deployment/deployment.md
      - OPA: deployment/opa_setup.md
      - Configuration File: config/configuration.md
      - Configuration Properties: config/properties.md
      - Monitoring, Events & Webhooks: deployment/monitoring.md
  - Developer Setup: developer_setup.md
  - Extending Moat: extensions.md
